### ISSUE TITLE
ImportError: cannot import name 'telegrambot' from 'AnonymousBot.botserver

### ISSUE THREAD

**Issue by adammshr09** [cvzi/chatanonymously#1]
ImportError: cannot import name 'telegrambot' from 'AnonymousBot.botserver hot to fix it

**Comment by cvzi** [comment]
I had not updated this in a long time. I don't use it anymore myself.

I updated the repository now and added install instruction to readme.

# Install and run
``` sh
git clone --recurse-submodules git@github.com:cvzi/chatanonymously.git
cd chatanonymously
pip install -r requirements.txt
python local.py
```
